services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    restart: always
    environment:
      - DOZZLE_NO_ANALYTICS=1
      # USER_PROVIDED_ENV_START
      # USER_PROVIDED_ENV_END
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - ${AF_DAZZLE_PORT:-9999}:8080

  adsb-setup-proxy:
    container_name: adsb-setup-proxy
    image: alpine
    stop_signal: SIGKILL
    command: tail -n500 -f /opt/adsb-setup.log
    volumes:
      - /opt/adsb/adsb-setup.log:/opt/adsb-setup.log
