services:
  piaware:
    image: ${FA_CONTAINER}
    tty: true
    container_name: piaware
    restart: always
    ports:
      - ${AF_PIAWAREMAP_PORT:-8081}:8080
      - ${AF_PIAWARESTAT_PORT:-8082}:80
    environment:
      - BEASTHOST=ultrafeeder
      - UAT_RECEIVER_TYPE=${FEEDER_PIAWARE_UAT978}
      - UAT_RECEIVER_HOST=${FEEDER_UAT978_HOST}
      - LAT=${FEEDER_LAT}
      - LONG=${FEEDER_LONG}
      - TZ=${FEEDER_TZ}
      - FEEDER_ID=${FEEDER_PIAWARE_FEEDER_ID}
      - S6_KILL_GRACETIME=1000
      # USER_PROVIDED_ENV_START
      # USER_PROVIDED_ENV_END
    tmpfs:
      - /run:exec,size=64M
      - /var/log
