volumes:
  radarbox_segfault_fix:
    driver: local
    driver_opts:
      type: none
      device: /opt/adsb/rb
      o: bind

services:
  rbfeeder:
    image: ${RB_CONTAINER}
    tty: true
    container_name: rbfeeder
    restart: always
    environment:
      - BEASTHOST=ultrafeeder
      - UAT_RECEIVER_HOST=${FEEDER_UAT978_HOST}
      - LAT=${FEEDER_LAT}
      - LONG=${FEEDER_LONG}
      - ALT=${FEEDER_ALT_M}
      - TZ=${FEEDER_TZ}
      - SHARING_KEY=${FEEDER_RADARBOX_SHARING_KEY}
      - S6_KILL_GRACETIME=1000
      # USER_PROVIDED_ENV_START
      # USER_PROVIDED_ENV_END
    tmpfs:
      - /run:exec,size=64M
      - /var/log
    volumes:
      - radarbox_segfault_fix:${FEEDER_RB_THERMAL_HACK:-/tmp/rbt}:ro
      - /opt/adsb/rb/cpuinfo:${FEEDER_RB_CPUINFO_HACK:-/tmp/rbc}:ro
